// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.1.0.0
//      SpecFlow Generator Version:3.1.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
// Generation customised by SpecFlow.Contrib.Variants
namespace WebAppAutomation.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("HomePage")]
    [NUnit.Framework.CategoryAttribute("HomePage")]
    [NUnit.Framework.CategoryAttribute("Browser:Chrome")]
    [NUnit.Framework.CategoryAttribute("Browser:Firefox")]
    public partial class HomePageFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "HomePage.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-GB"), "HomePage", "\tIn order to test static contents\r\n\tI successfully logged in\r\n\tI navigate to home" +
                    " page\r\n\tI check static contents", ProgrammingLanguage.CSharp, new string[] {
                        "HomePage",
                        "Browser:Chrome",
                        "Browser:Firefox"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
            testRunner.Given("I Navigate to the Login page \'https://demo.mycsf.net/Portal/Home/Login\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Password"});
            table1.AddRow(new string[] {
                        "actu4205@gmail.com",
                        "Hitrust123!"});
            testRunner.When("I enter Email and Password", ((string)(null)), table1, "When ");
            testRunner.And("I click on Login button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "AppLandingPage"});
            table2.AddRow(new string[] {
                        "https://demo.mycsf.net/Portal/Home/AppLanding"});
            testRunner.Then("I navigate to landing page", ((string)(null)), table2, "Then ");
            testRunner.And("I click on app button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Home page automation: Chrome")]
        [NUnit.Framework.CategoryAttribute("Browser:Chrome")]
        [NUnit.Framework.CategoryAttribute("regression")]
        public virtual void HomePageAutomation_Chrome()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Home page automation", null, new string[] {
                        "regression"});
            this.ScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.Add("Browser", "Chrome");
            this.ScenarioStart();
            this.FeatureBackground();
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "HomePage"});
            table3.AddRow(new string[] {
                        "https://demo.mycsf.net/Home3"});
            testRunner.Given("navigate to home page", ((string)(null)), table3, "Given ");
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "NavBars"});
            table4.AddRow(new string[] {
                        "HOME"});
            table4.AddRow(new string[] {
                        "REFERENCES"});
            table4.AddRow(new string[] {
                        "ANALYTICS"});
            table4.AddRow(new string[] {
                        "CORRECTIVE ACTION PLANS"});
            table4.AddRow(new string[] {
                        "ADMINISTRATION"});
            table4.AddRow(new string[] {
                        "SEARCH"});
            testRunner.Then("there should be nav bars", ((string)(null)), table4, "Then ");
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Texts"});
            table5.AddRow(new string[] {
                        "YOUR NOTIFICATIONS"});
            table5.AddRow(new string[] {
                        "ASSESSMENTS"});
            table5.AddRow(new string[] {
                        "CUSTOM LIBRARIES"});
            table5.AddRow(new string[] {
                        "BULLETINS"});
            testRunner.And("the static texts are", ((string)(null)), table5, "And ");
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Home page automation: Firefox")]
        [NUnit.Framework.CategoryAttribute("Browser:Firefox")]
        [NUnit.Framework.CategoryAttribute("regression")]
        public virtual void HomePageAutomation_Firefox()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Home page automation", null, new string[] {
                        "regression"});
            this.ScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.Add("Browser", "Firefox");
            this.ScenarioStart();
            this.FeatureBackground();
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "HomePage"});
            table6.AddRow(new string[] {
                        "https://demo.mycsf.net/Home3"});
            testRunner.Given("navigate to home page", ((string)(null)), table6, "Given ");
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "NavBars"});
            table7.AddRow(new string[] {
                        "HOME"});
            table7.AddRow(new string[] {
                        "REFERENCES"});
            table7.AddRow(new string[] {
                        "ANALYTICS"});
            table7.AddRow(new string[] {
                        "CORRECTIVE ACTION PLANS"});
            table7.AddRow(new string[] {
                        "ADMINISTRATION"});
            table7.AddRow(new string[] {
                        "SEARCH"});
            testRunner.Then("there should be nav bars", ((string)(null)), table7, "Then ");
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Texts"});
            table8.AddRow(new string[] {
                        "YOUR NOTIFICATIONS"});
            table8.AddRow(new string[] {
                        "ASSESSMENTS"});
            table8.AddRow(new string[] {
                        "CUSTOM LIBRARIES"});
            table8.AddRow(new string[] {
                        "BULLETINS"});
            testRunner.And("the static texts are", ((string)(null)), table8, "And ");
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
